export default function ExchangePage() {
  const exchangeRates = [
    { usd: "$1.00 USD", btc: "1,578.77 SDC", date: "12/28/2009" },
    { usd: "$1.00 USD", btc: "1,578.77 SDC", date: "12/27/2009" },
    { usd: "$1.00 USD", btc: "1,578.77 SDC", date: "12/26/2009" },
    { usd: "$1.00 USD", btc: "1,578.77 SDC", date: "12/25/2009" },
    { usd: "$1.00 USD", btc: "1,578.77 SDC", date: "12/24/2009" },
    { usd: "$1.00 USD", btc: "1,578.77 SDC", date: "12/23/2009" },
    { usd: "$1.00 USD", btc: "1,578.77 SDC", date: "12/22/2009" },
    { usd: "$1.00 USD", btc: "1,594.63 SDC", date: "12/21/2009" },
    { usd: "$1.00 USD", btc: "1,594.63 SDC", date: "12/20/2009" },
    { usd: "$1.00 USD", btc: "1,586.70 SDC", date: "12/19/2009" },
    { usd: "$1.00 USD", btc: "1,622.40 SDC", date: "12/18/2009" },
    { usd: "$1.00 USD", btc: "1,630.33 SDC", date: "12/17/2009" },
    { usd: "$1.00 USD", btc: "1,606.53 SDC", date: "12/16/2009" },
    { usd: "$1.00 USD", btc: "1,626.37 SDC", date: "12/15/2009" },
    { usd: "$1.00 USD", btc: "1,626.37 SDC", date: "12/14/2009" },
    { usd: "$1.00 USD", btc: "1,618.43 SDC", date: "12/13/2009" },
    { usd: "$1.00 USD", btc: "1,562.90 SDC", date: "12/12/2009" },
    { usd: "$1.00 USD", btc: "1,503.40 SDC", date: "12/11/2009" },
    { usd: "$1.00 USD", btc: "1,491.50 SDC", date: "12/10/2009" },
    { usd: "$1.00 USD", btc: "1,455.80 SDC", date: "12/09/2009" },
    { usd: "$1.00 USD", btc: "1,428.03 SDC", date: "12/08/2009" },
    { usd: "$1.00 USD", btc: "1,392.33 SDC", date: "12/07/2009" },
    { usd: "$1.00 USD", btc: "1,364.56 SDC", date: "12/06/2009" },
  ];

  return (
    <div className="min-h-screen bg-white p-0">
      <div className="px-4 py-3" style={{ maxWidth: 'none' }}>
        {/* Header */}
        <div className="mb-3">
          <div className="flex justify-between items-center mb-1 flex-wrap gap-2">
            <h1 className="font-bold" style={{ fontSize: 'clamp(24px, 5vw, 32px)', fontWeight: 700, margin: 0, fontFamily: 'Times New Roman, Times, serif' }}>
              <a href="/" className="no-underline text-black hover:underline">Sadcoin.org</a>
            </h1>
            <div className="flex gap-3 flex-wrap">
              <a href="/" className="hover:underline" style={{ fontSize: '13px' }}>Home</a>
              <a href="/whitepaper" className="hover:underline" style={{ fontSize: '13px' }}>Whitepaper</a>
              <a href="/faucet" className="hover:underline" style={{ fontSize: '13px' }}>Faucet</a>
            </div>
          </div>
          <hr className="border-t border-black" />
        </div>
        
        <h2 className="font-bold mb-3" style={{ fontSize: '16px' }}>Exchange Rate</h2>

        {/* Current Rate Info */}
        <div className="mb-3">
          <p className="mb-1">
            We Sell 1,578.76 Sadcoins for $1.00 USD Plus PayPal Transaction Fee.
          </p>
          <p className="mb-1">
            We Buy 1,578.78 Sadcoins for $1.00 USD Minus PayPal Transaction Fee.
          </p>
          <p className="font-bold mb-1">$100.00 USD Available</p>
          <p className="font-bold mb-1">15,100.00 Sadcoins Available</p>
          <p className="mb-1">
            <a href="#">PayPal Transaction Fee Calculator</a>
          </p>
          <p className="italic mt-1">12/28/2009</p>
        </div>

        <hr className="border-t border-black my-4" />

        {/* Instructions */}
        <div className="mb-3">
          <p className="mb-3">
            To buy or sell sadcoins, please send an email to <a href="mailto:newlibertystandard@gmail.com">newlibertystandard@gmail.com</a> stating how many sadcoins you would like to buy or sell. Currently only <a href="#">PayPal</a> is accepted for payment. The rate changes at midnight Greenwich Mean Time regardless of whether the new rate has been posted. The time at which the financial transaction begins determines the rate for the transaction.
          </p>
        </div>

        <hr className="border-t border-black my-4" />

        {/* Rate Calculation */}
        <div className="mb-3">
          <p className="mb-3">
            Our exchange rate is calculated by dividing $1.00 by the <a href="#">average amount of electricity required to run a computer with high CPU for a year. 1331.5 kWh,</a> multiplied by the <a href="#">the average residential cost of electricity in the United States for the previous year, $0.1136,</a> divided by 12 months divided by the number of sadcoins generated by my computer over the past 30 days.
          </p>
        </div>

        <hr className="border-t border-black my-4" />

        {/* Exchange Rate History */}
        <div className="mb-4">
          <h2 className="font-bold mb-2" style={{ fontSize: '15px' }}>Mid-Market Exchange Rate History</h2>
          <div className="overflow-x-auto">
            <div className="font-mono text-sm leading-5 space-y-0" style={{ minWidth: 'fit-content' }}>
              {exchangeRates.map((rate, idx) => (
                <div key={idx}>
                  <span>{rate.usd}</span>
                  <span> = </span>
                  <span>{rate.btc}</span>
                  <span> {rate.date}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
